/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'age' : bigint,
  'sex' : string,
  'occupation' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'income' : [] | [bigint],
  'phone' : [] | [string],
}
export interface Goal {
  'id' : bigint,
  'annualSIPStepUp' : number,
  'clientId' : bigint,
  'inflationRate' : number,
  'simCount' : bigint,
  'strategy' : string,
  'annualSIP' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'presentValue' : bigint,
  'lumpSum' : bigint,
  'updatedAt' : bigint,
  'monthlySIPStepUp' : number,
  'timeHorizon' : bigint,
  'monthlySIP' : bigint,
  'strategyMean' : number,
  'strategySD' : number,
}
export interface _SERVICE {
  'createClient' : ActorMethod<
    [
      string,
      bigint,
      string,
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'createGoal' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      number,
      bigint,
      string,
      number,
      number,
      bigint,
      bigint,
      number,
      bigint,
      number,
      bigint,
    ],
    bigint
  >,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getGoal' : ActorMethod<[bigint], Goal>,
  'listAllGoals' : ActorMethod<[], Array<Goal>>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listGoalsByClient' : ActorMethod<[bigint], Array<Goal>>,
  'updateClient' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateGoal' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      bigint,
      number,
      bigint,
      string,
      number,
      number,
      bigint,
      bigint,
      number,
      bigint,
      number,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];