/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'sex' : IDL.Text,
  'occupation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'income' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Opt(IDL.Text),
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'annualSIPStepUp' : IDL.Float64,
  'clientId' : IDL.Nat,
  'inflationRate' : IDL.Float64,
  'simCount' : IDL.Nat,
  'strategy' : IDL.Text,
  'annualSIP' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'presentValue' : IDL.Nat,
  'lumpSum' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'monthlySIPStepUp' : IDL.Float64,
  'timeHorizon' : IDL.Nat,
  'monthlySIP' : IDL.Nat,
  'strategyMean' : IDL.Float64,
  'strategySD' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createGoal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
  'listAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listGoalsByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Goal)], ['query']),
  'updateClient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateGoal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'sex' : IDL.Text,
    'occupation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'income' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'annualSIPStepUp' : IDL.Float64,
    'clientId' : IDL.Nat,
    'inflationRate' : IDL.Float64,
    'simCount' : IDL.Nat,
    'strategy' : IDL.Text,
    'annualSIP' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'presentValue' : IDL.Nat,
    'lumpSum' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'monthlySIPStepUp' : IDL.Float64,
    'timeHorizon' : IDL.Nat,
    'monthlySIP' : IDL.Nat,
    'strategyMean' : IDL.Float64,
    'strategySD' : IDL.Float64,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createGoal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
    'listAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listGoalsByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Goal)], ['query']),
    'updateClient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateGoal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };